HOSTNAME = "127.0.0.1"
PORT = 5432
USERNAME = "yiming"
PASSWORD = "root"
DATABASE = "cards"
DB_URI = f"postgresql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}"
SQLALCHEMY_DATABASE_URI = DB_URI
